# Generated by Django 4.1.7 on 2023-03-17 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0002_remove_product_category"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Product',
                    fields=[
                        (
                            'id',
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name='ID',
                            ),
                        ),
                        (
                            'name',
                            models.CharField(db_index=True, max_length=100),
                        ),
                        (
                            'category',
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to='catalog.Category',
                            ),
                        ),
                    ],
                    options={
                        'db_table': 'catalog_product',
                    },
                ),
            ],
            # You reference an existing table
            database_operations=[],
        ),
    ]
