# Generated by Django 4.1.7 on 2023-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='product',
                    name='category',
                ),
            ],
            # You're reusing the table, so don't drop it
            database_operations=[],
        ),
    ]
