# Generated by Django 4.1.7 on 2023-03-17 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_alter_product_category"),
        ("sale", "0002_alter_sale_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
