# Generated by Django 4.1.7 on 2023-03-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_auto_20230317_0903"),
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="product.product"
            ),
        ),
    ]
